repos:
  - repo: https://github.com/charliermarsh/ruff
    rev: "v0.0.288"
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3.11
