"""added passive_deletes true for notification deletion

Revision ID: 1ddec7fce36e
Revises: 7bef9fc96a37
Create Date: 2026-03-05 18:01:46.075844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ddec7fce36e'
down_revision: Union[str, Sequence[str], None] = '7bef9fc96a37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
