"""pulled table changes podgoal table updated

Revision ID: 1f027b2ab9a9
Revises: ef301c9f4cb6
Create Date: 2026-01-29 17:46:28.820490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f027b2ab9a9'
down_revision: Union[str, Sequence[str], None] = 'ef301c9f4cb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pod_goals', sa.Column('requires_measurement', sa.Boolean(), nullable=True))
    op.add_column('pod_goals', sa.Column('measurement_unit', sa.String(), nullable=True))
    op.add_column('pod_goals', sa.Column('measurement_target', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pod_goals', 'measurement_target')
    op.drop_column('pod_goals', 'measurement_unit')
    op.drop_column('pod_goals', 'requires_measurement')
    # ### end Alembic commands ###
