"""added ondelete model cascade on goalprogressevent on user_id

Revision ID: 32d091642012
Revises: 534fd0c4b27d
Create Date: 2026-03-10 12:52:52.069041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32d091642012'
down_revision: Union[str, Sequence[str], None] = '534fd0c4b27d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('goal_progress_events_user_id_fkey'), 'goal_progress_events', type_='foreignkey')
    op.create_foreign_key(None, 'goal_progress_events', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'goal_progress_events', type_='foreignkey')
    op.create_foreign_key(op.f('goal_progress_events_user_id_fkey'), 'goal_progress_events', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
