"""added backref to delete related notification when user deleted

Revision ID: 534fd0c4b27d
Revises: 94bc4a3cb40e
Create Date: 2026-03-10 12:45:28.443806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '534fd0c4b27d'
down_revision: Union[str, Sequence[str], None] = '94bc4a3cb40e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
