"""created activity log table

Revision ID: 5786666eb971
Revises: 4a773069a72f
Create Date: 2026-03-03 12:28:15.893910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5786666eb971'
down_revision: Union[str, Sequence[str], None] = '4a773069a72f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('pod_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=500), nullable=False),
    sa.Column('details', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pod_id'], ['pods.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
