"""added on delete cascade on reflection id 

Revision ID: 5aa3c7df3896
Revises: 1ddec7fce36e
Create Date: 2026-03-09 14:58:35.543733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5aa3c7df3896'
down_revision: Union[str, Sequence[str], None] = '1ddec7fce36e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('goal_progress_events_reflection_id_fkey'), 'goal_progress_events', type_='foreignkey')
    op.create_foreign_key(None, 'goal_progress_events', 'reflections', ['reflection_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'goal_progress_events', type_='foreignkey')
    op.create_foreign_key(op.f('goal_progress_events_reflection_id_fkey'), 'goal_progress_events', 'reflections', ['reflection_id'], ['id'])
    # ### end Alembic commands ###
