"""modified column name progress_value to weekly_progress_value at reflectiongoal table

Revision ID: 646968b5f463
Revises: 1f027b2ab9a9
Create Date: 2026-02-03 11:57:23.833208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '646968b5f463'
down_revision: Union[str, Sequence[str], None] = '1f027b2ab9a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reflection_goals', sa.Column('weekly_progress_value', sa.Float(), nullable=True))
    op.drop_column('reflection_goals', 'progress_value')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reflection_goals', sa.Column('progress_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('reflection_goals', 'weekly_progress_value')
    # ### end Alembic commands ###
