"""added column for related field in activity log table 

Revision ID: 94bc4a3cb40e
Revises: 5aa3c7df3896
Create Date: 2026-03-09 15:31:13.579543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94bc4a3cb40e'
down_revision: Union[str, Sequence[str], None] = '5aa3c7df3896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_logs', sa.Column('target_ids', postgresql.ARRAY(sa.UUID()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_logs', 'target_ids')
    # ### end Alembic commands ###
