"""Initial schema setup

Revision ID: ef301c9f4cb6
Revises: 
Create Date: 2026-01-22 14:03:01.048776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef301c9f4cb6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=45), nullable=True),
    sa.Column('country_code', sa.String(length=5), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_onboarded', sa.Boolean(), nullable=True),
    sa.Column('verification_token', sa.String(), nullable=True),
    sa.Column('reset_token', sa.String(), nullable=True),
    sa.Column('profile_photo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('firebase_uid')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('notification_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('focus_area', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('max_members', sa.Integer(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('invite_code', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code')
    )
    op.create_table('sms_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=25), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('provider_message_id', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('checkin_frequency', sa.String(length=20), nullable=False),
    sa.Column('checkin_time', sa.Time(), nullable=True),
    sa.Column('pod_updates_enabled', sa.Boolean(), nullable=False),
    sa.Column('reminder', sa.Boolean(), nullable=True),
    sa.Column('sms_reminder', sa.Boolean(), nullable=True),
    sa.Column('photo_expiration', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('pod_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pod_id'], ['pods.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_created', 'notifications', ['created_at'], unique=False)
    op.create_index('idx_notifications_user', 'notifications', ['user_id'], unique=False)
    op.create_index('idx_notifications_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('pod_goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pod_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('why_it_matters', sa.Text(), nullable=True),
    sa.Column('success_definition', sa.Text(), nullable=True),
    sa.Column('frequency_type', sa.String(), nullable=True),
    sa.Column('frequency_value', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pod_id'], ['pods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pod_goals_category', 'pod_goals', ['category'], unique=False)
    op.create_index('idx_pod_goals_frequency', 'pod_goals', ['frequency_type'], unique=False)
    op.create_index('idx_pod_goals_pod', 'pod_goals', ['pod_id'], unique=False)
    op.create_index('idx_pod_goals_status', 'pod_goals', ['status'], unique=False)
    op.create_table('pod_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pod_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('joined_via', sa.String(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['pod_id'], ['pods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pod_id', 'user_id')
    )
    op.create_table('pod_settings',
    sa.Column('pod_id', sa.UUID(), nullable=False),
    sa.Column('allow_invites', sa.Boolean(), nullable=True),
    sa.Column('allow_member_posts', sa.Boolean(), nullable=True),
    sa.Column('weekly_summary_enabled', sa.Boolean(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pod_id'], ['pods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pod_id')
    )
    op.create_table('reflections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pod_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('reflection_date', sa.Date(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('mood', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pod_id'], ['pods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reflections_date', 'reflections', ['reflection_date'], unique=False)
    op.create_index('idx_reflections_pod', 'reflections', ['pod_id'], unique=False)
    op.create_index('idx_reflections_user', 'reflections', ['user_id'], unique=False)
    op.create_index('idx_reflections_user_date', 'reflections', ['user_id', 'reflection_date'], unique=False)
    op.create_table('goal_progress_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pod_id', sa.UUID(), nullable=True),
    sa.Column('goal_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('reflection_id', sa.UUID(), nullable=True),
    sa.Column('progress_date', sa.Date(), nullable=False),
    sa.Column('frequency_type', sa.String(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('progress_value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['pod_goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pod_id'], ['pods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reflection_id'], ['reflections.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_progress_date', 'goal_progress_events', ['progress_date'], unique=False)
    op.create_index('idx_progress_goal', 'goal_progress_events', ['goal_id'], unique=False)
    op.create_index('idx_progress_user', 'goal_progress_events', ['user_id'], unique=False)
    op.create_index('idx_progress_user_goal', 'goal_progress_events', ['user_id', 'goal_id'], unique=False)
    op.create_index('idx_progress_user_goal_date', 'goal_progress_events', ['user_id', 'goal_id', 'progress_date'], unique=False)
    op.create_table('goal_streaks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('goal_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('longest_streak', sa.Integer(), nullable=True),
    sa.Column('last_completed_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['pod_goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('goal_id', 'user_id')
    )
    op.create_index('idx_streaks_goal', 'goal_streaks', ['goal_id'], unique=False)
    op.create_index('idx_streaks_user', 'goal_streaks', ['user_id'], unique=False)
    op.create_table('pod_goal_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pod_id', sa.UUID(), nullable=True),
    sa.Column('goal_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('joined_at', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['pod_goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pod_id'], ['pods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('goal_id', 'user_id')
    )
    op.create_index('idx_goal_participants_active', 'pod_goal_participants', ['is_active'], unique=False)
    op.create_index('idx_goal_participants_goal', 'pod_goal_participants', ['goal_id'], unique=False)
    op.create_index('idx_goal_participants_user', 'pod_goal_participants', ['user_id'], unique=False)
    op.create_table('reflection_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reflection_id', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['reflection_id'], ['reflections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reflection_attachments_reflection', 'reflection_attachments', ['reflection_id'], unique=False)
    op.create_index('idx_reflection_attachments_type', 'reflection_attachments', ['file_type'], unique=False)
    op.create_table('reflection_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reflection_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['reflection_id'], ['reflections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reflection_comments_created', 'reflection_comments', ['created_at'], unique=False)
    op.create_index('idx_reflection_comments_reflection', 'reflection_comments', ['reflection_id'], unique=False)
    op.create_index('idx_reflection_comments_user', 'reflection_comments', ['user_id'], unique=False)
    op.create_table('reflection_goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reflection_id', sa.UUID(), nullable=True),
    sa.Column('goal_id', sa.UUID(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('progress_value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['pod_goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reflection_id'], ['reflections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reflection_goals_completed', 'reflection_goals', ['completed'], unique=False)
    op.create_index('idx_reflection_goals_goal', 'reflection_goals', ['goal_id'], unique=False)
    op.create_index('idx_reflection_goals_reflection', 'reflection_goals', ['reflection_id'], unique=False)
    op.create_table('reflection_reactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reflection_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reaction', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['reflection_id'], ['reflections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reflection_id', 'user_id', 'reaction')
    )
    op.create_index('idx_reflection_reactions_reaction', 'reflection_reactions', ['reaction'], unique=False)
    op.create_index('idx_reflection_reactions_reflection', 'reflection_reactions', ['reflection_id'], unique=False)
    op.create_index('idx_reflection_reactions_user', 'reflection_reactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reflection_reactions_user', table_name='reflection_reactions')
    op.drop_index('idx_reflection_reactions_reflection', table_name='reflection_reactions')
    op.drop_index('idx_reflection_reactions_reaction', table_name='reflection_reactions')
    op.drop_table('reflection_reactions')
    op.drop_index('idx_reflection_goals_reflection', table_name='reflection_goals')
    op.drop_index('idx_reflection_goals_goal', table_name='reflection_goals')
    op.drop_index('idx_reflection_goals_completed', table_name='reflection_goals')
    op.drop_table('reflection_goals')
    op.drop_index('idx_reflection_comments_user', table_name='reflection_comments')
    op.drop_index('idx_reflection_comments_reflection', table_name='reflection_comments')
    op.drop_index('idx_reflection_comments_created', table_name='reflection_comments')
    op.drop_table('reflection_comments')
    op.drop_index('idx_reflection_attachments_type', table_name='reflection_attachments')
    op.drop_index('idx_reflection_attachments_reflection', table_name='reflection_attachments')
    op.drop_table('reflection_attachments')
    op.drop_index('idx_goal_participants_user', table_name='pod_goal_participants')
    op.drop_index('idx_goal_participants_goal', table_name='pod_goal_participants')
    op.drop_index('idx_goal_participants_active', table_name='pod_goal_participants')
    op.drop_table('pod_goal_participants')
    op.drop_index('idx_streaks_user', table_name='goal_streaks')
    op.drop_index('idx_streaks_goal', table_name='goal_streaks')
    op.drop_table('goal_streaks')
    op.drop_index('idx_progress_user_goal_date', table_name='goal_progress_events')
    op.drop_index('idx_progress_user_goal', table_name='goal_progress_events')
    op.drop_index('idx_progress_user', table_name='goal_progress_events')
    op.drop_index('idx_progress_goal', table_name='goal_progress_events')
    op.drop_index('idx_progress_date', table_name='goal_progress_events')
    op.drop_table('goal_progress_events')
    op.drop_index('idx_reflections_user_date', table_name='reflections')
    op.drop_index('idx_reflections_user', table_name='reflections')
    op.drop_index('idx_reflections_pod', table_name='reflections')
    op.drop_index('idx_reflections_date', table_name='reflections')
    op.drop_table('reflections')
    op.drop_table('pod_settings')
    op.drop_table('pod_members')
    op.drop_index('idx_pod_goals_status', table_name='pod_goals')
    op.drop_index('idx_pod_goals_pod', table_name='pod_goals')
    op.drop_index('idx_pod_goals_frequency', table_name='pod_goals')
    op.drop_index('idx_pod_goals_category', table_name='pod_goals')
    op.drop_table('pod_goals')
    op.drop_index('idx_notifications_user_read', table_name='notifications')
    op.drop_index('idx_notifications_user', table_name='notifications')
    op.drop_index('idx_notifications_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('user_preferences')
    op.drop_table('sms_logs')
    op.drop_table('pods')
    op.drop_table('notification_tokens')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
