"""create reflection embeddings table

Revision ID: f2d53fcfe194
Revises: 4e21a268d90f
Create Date: 2026-08-08 13:02:12.821200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2d53fcfe194'
down_revision: Union[str, Sequence[str], None] = '4e21a268d90f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reflection_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reflection_id', sa.UUID(), nullable=False),
    sa.Column('embedding', postgresql.ARRAY(sa.Float()), nullable=False),
    sa.ForeignKeyConstraint(['reflection_id'], ['reflections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reflection_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reflection_embeddings')
    # ### end Alembic commands ###
